# This is currently in the wrong directory!
# switch this file with the current years makefile in the root directory in order to use

all:
	@echo "Welcome to the Advent of Code for 2019!"
	@echo "You will find commands to run each day individually,"
	@echo "enjoy looking around and think about joining next year!"

day1:
	python3 -m 2019.1stDay.fuelCost part1
	python3 -m 2019.1stDay.fuelCost part2

day2:
	python3 -m 2019.2ndDay.intcode part1
	python3 -m 2019.2ndDay.intcode part2

day3:
	python3 -m 2019.3rdDay.manhatten part1
	python3 -m 2019.3rdDay.manhatten part2

day4:
	python3 -m 2019.4thDay.password part1
	python3 -m 2019.4thDay.password part2

day5:
	python3 -m 2019.5thDay.diagnostic part1
	python3 -m 2019.5thDay.diagnostic part2

day6:
	python3 -m 2019.6thDay.orbits part1
	python3 -m 2019.6thDay.orbits part2

day7:
	python3 -m 2019.7thDay.amplifiers part1
	python3 -m 2019.7thDay.amplifiers part2
	
day8:
	python3 -m 2019.8thDay.images part1
	python3 -m 2019.8thDay.images part2

day9:
	python3 -m 2019.9thDay.boostProgram part1
	python3 -m 2019.9thDay.boostProgram part2
